// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoskjrhjaimyyhzthkdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvc2tqcmhqYWlteXloenRoa2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTYxMzcsImV4cCI6MjA3MjA3MjEzN30.Qahoat3idnlZb767mQd2gzosWrL1PEfxWHPVYaPsGzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});